// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeodbej261yvaugFEqmp022C-0VvyXCJE',
    appId: '1:258109170144:web:486cfbf10faf9d0521cb85',
    messagingSenderId: '258109170144',
    projectId: 'demoproject-5aef1',
    authDomain: 'demoproject-5aef1.firebaseapp.com',
    storageBucket: 'demoproject-5aef1.firebasestorage.app',
    measurementId: 'G-HHZN8E98CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC1SVA2c5pFvHWemUGbrB-g5q7ErF-_20',
    appId: '1:258109170144:android:2c34ad4d1e2a377921cb85',
    messagingSenderId: '258109170144',
    projectId: 'demoproject-5aef1',
    storageBucket: 'demoproject-5aef1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkIgTLdITXWD4AFH23DPH9nIiK9IX6Q8w',
    appId: '1:258109170144:ios:69ea702a1e99a35021cb85',
    messagingSenderId: '258109170144',
    projectId: 'demoproject-5aef1',
    storageBucket: 'demoproject-5aef1.firebasestorage.app',
    iosBundleId: 'com.example.busboking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkIgTLdITXWD4AFH23DPH9nIiK9IX6Q8w',
    appId: '1:258109170144:ios:69ea702a1e99a35021cb85',
    messagingSenderId: '258109170144',
    projectId: 'demoproject-5aef1',
    storageBucket: 'demoproject-5aef1.firebasestorage.app',
    iosBundleId: 'com.example.busboking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeodbej261yvaugFEqmp022C-0VvyXCJE',
    appId: '1:258109170144:web:93e751963927b92f21cb85',
    messagingSenderId: '258109170144',
    projectId: 'demoproject-5aef1',
    authDomain: 'demoproject-5aef1.firebaseapp.com',
    storageBucket: 'demoproject-5aef1.firebasestorage.app',
    measurementId: 'G-EE4GEJEBPK',
  );

}