// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7VOlzscnlREtWEdf-m_azOsxJciybcfg',
    appId: '1:55875068864:web:a94f4249634c483d609e25',
    messagingSenderId: '55875068864',
    projectId: 'busbookingapp-5b81c',
    authDomain: 'busbookingapp-5b81c.firebaseapp.com',
    databaseURL: 'https://busbookingapp-5b81c-default-rtdb.firebaseio.com',
    storageBucket: 'busbookingapp-5b81c.firebasestorage.app',
    measurementId: 'G-MJ5QXTT1RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYlhbV0jj_Avhe60lmXFha0to-1ALXNYs',
    appId: '1:55875068864:android:2fdca9c89f5db07f609e25',
    messagingSenderId: '55875068864',
    projectId: 'busbookingapp-5b81c',
    databaseURL: 'https://busbookingapp-5b81c-default-rtdb.firebaseio.com',
    storageBucket: 'busbookingapp-5b81c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPj8sS4J-ZoPEqR4GXCX-jt88lQwRLbjs',
    appId: '1:55875068864:ios:0fd4d5d326f6e2be609e25',
    messagingSenderId: '55875068864',
    projectId: 'busbookingapp-5b81c',
    databaseURL: 'https://busbookingapp-5b81c-default-rtdb.firebaseio.com',
    storageBucket: 'busbookingapp-5b81c.firebasestorage.app',
    iosBundleId: 'com.example.busboking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPj8sS4J-ZoPEqR4GXCX-jt88lQwRLbjs',
    appId: '1:55875068864:ios:0fd4d5d326f6e2be609e25',
    messagingSenderId: '55875068864',
    projectId: 'busbookingapp-5b81c',
    databaseURL: 'https://busbookingapp-5b81c-default-rtdb.firebaseio.com',
    storageBucket: 'busbookingapp-5b81c.firebasestorage.app',
    iosBundleId: 'com.example.busboking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7VOlzscnlREtWEdf-m_azOsxJciybcfg',
    appId: '1:55875068864:web:0445a27d9c030ab6609e25',
    messagingSenderId: '55875068864',
    projectId: 'busbookingapp-5b81c',
    authDomain: 'busbookingapp-5b81c.firebaseapp.com',
    databaseURL: 'https://busbookingapp-5b81c-default-rtdb.firebaseio.com',
    storageBucket: 'busbookingapp-5b81c.firebasestorage.app',
    measurementId: 'G-2L7Y2ZES8G',
  );

}